/*
  Auto-generated by Spline
*/

import useSpline from '@splinetool/r3f-spline'
import { PerspectiveCamera } from '@react-three/drei'

export default function Scene({ ...props }) {
  const { nodes, materials } = useSpline('https://prod.spline.design/90Yi9N-dAHhFegtQ/scene.splinecode')
  return (
    <>
      <color attach="background" args={['#809ce8']} />
      <group {...props} dispose={null}>
        <group name="Crown">
          <mesh
            name="Rectangle 21"
            geometry={nodes['Rectangle 21'].geometry}
            material={materials['Rectangle 21 Material']}
            castShadow
            receiveShadow
            position={[-0.36, -116.65, -25]}
          />
          <mesh
            name="Rectangle 20"
            geometry={nodes['Rectangle 20'].geometry}
            material={materials['Rectangle 20 Material']}
            castShadow
            receiveShadow
            position={[-90.37, -156.38, -25]}
          />
          <mesh
            name="Rectangle 19"
            geometry={nodes['Rectangle 19'].geometry}
            material={materials['Rectangle 19 Material']}
            castShadow
            receiveShadow
            position={[-170.53, -8.27, -25]}
          />
          <mesh
            name="Rectangle 18"
            geometry={nodes['Rectangle 18'].geometry}
            material={materials['Rectangle 18 Material']}
            castShadow
            receiveShadow
            position={[-147.53, 21.62, -25]}
          />
          <mesh
            name="Rectangle 17"
            geometry={nodes['Rectangle 17'].geometry}
            material={materials['Rectangle 17 Material']}
            castShadow
            receiveShadow
            position={[-143.53, 91.62, -25]}
          />
          <mesh
            name="Rectangle 16"
            geometry={nodes['Rectangle 16'].geometry}
            material={materials['Rectangle 16 Material']}
            castShadow
            receiveShadow
            position={[-195.53, 117.62, -25]}
          />
          <mesh
            name="Rectangle 14"
            geometry={nodes['Rectangle 14'].geometry}
            material={materials['Rectangle 14 Material']}
            castShadow
            receiveShadow
            position={[-110.53, -31.38, -25]}
          />
          <mesh
            name="Rectangle 13"
            geometry={nodes['Rectangle 13'].geometry}
            material={materials['Rectangle 13 Material']}
            castShadow
            receiveShadow
            position={[-66.53, -8.38, -25]}
          />
          <mesh
            name="Rectangle 12"
            geometry={nodes['Rectangle 12'].geometry}
            material={materials['Rectangle 12 Material']}
            castShadow
            receiveShadow
            position={[-29.53, 29.62, -25]}
          />
          <mesh
            name="Rectangle 11"
            geometry={nodes['Rectangle 11'].geometry}
            material={materials['Rectangle 11 Material']}
            castShadow
            receiveShadow
            position={[-56.53, 108.62, -25]}
          />
          <mesh
            name="Rectangle 10"
            geometry={nodes['Rectangle 10'].geometry}
            material={materials['Rectangle 10 Material']}
            castShadow
            receiveShadow
            position={[-10.53, 143.62, -25]}
          />
          <mesh
            name="Rectangle 9"
            geometry={nodes['Rectangle 9'].geometry}
            material={materials['Rectangle 9 Material']}
            castShadow
            receiveShadow
            position={[30.47, 110.62, -25]}
          />
          <mesh
            name="Rectangle 8"
            geometry={nodes['Rectangle 8'].geometry}
            material={materials['Rectangle 8 Material']}
            castShadow
            receiveShadow
            position={[25.47, -3.38, -25]}
          />
          <mesh
            name="Rectangle 6"
            geometry={nodes['Rectangle 6'].geometry}
            material={materials['Rectangle 6 Material']}
            castShadow
            receiveShadow
            position={[-4.53, 39.62, -25]}
          />
          <mesh
            name="Rectangle 5"
            geometry={nodes['Rectangle 5'].geometry}
            material={materials['Rectangle 5 Material']}
            castShadow
            receiveShadow
            position={[113.63, 51.62, -25]}
          />
          <mesh
            name="Rectangle 4"
            geometry={nodes['Rectangle 4'].geometry}
            material={materials['Rectangle 4 Material']}
            castShadow
            receiveShadow
            position={[164.63, 71.62, -25]}
          />
          <mesh
            name="Rectangle 3"
            geometry={nodes['Rectangle 3'].geometry}
            material={materials['Rectangle 3 Material']}
            castShadow
            receiveShadow
            position={[126.63, -33.38, -25]}
          />
          <mesh
            name="Rectangle 2"
            geometry={nodes['Rectangle 2'].geometry}
            material={materials['Rectangle 2 Material']}
            castShadow
            receiveShadow
            position={[126.63, -33.38, -25]}
          />
          <mesh
            name="Rectangle"
            geometry={nodes.Rectangle.geometry}
            material={materials['Rectangle Material']}
            castShadow
            receiveShadow
            position={[76.47, -25.38, -25]}
          />
        </group>
        <directionalLight
          name="Directional Light"
          castShadow
          intensity={0.7}
          shadow-mapSize-width={1024}
          shadow-mapSize-height={1024}
          shadow-camera-near={-10000}
          shadow-camera-far={100000}
          shadow-camera-left={-1000}
          shadow-camera-right={1000}
          shadow-camera-top={1000}
          shadow-camera-bottom={-1000}
          position={[200, 300, 300]}
        />
        <PerspectiveCamera
          name="1"
          makeDefault={true}
          far={100000}
          near={70}
          fov={45}
          position={[577.35, 577.35, 577.35]}
          rotation={[-Math.PI / 4, 0.62, Math.PI / 6]}
          scale={1}
        />
        <hemisphereLight name="Default Ambient Light" intensity={0.75} color="#eaeaea" />
      </group>
    </>
  )
}
